yamada-ui/yamada-colors

pages/palettes/[uuid]/hex-control-buttons.tsx, pages/palettes/[uuid]/hexes.tsx
Fixed a bug in `forwardRef`.
No
=> Fixed a bug in `forwardRef`

.github/pull_request_template.md, scripts/observe-pull-requests.ts
Update terminology in PR process docs.
No
=> Update terminology in PR process docs

package.json, pnpm-lock.yaml, scripts/observe-pull-requests.ts, scripts/utils.ts
Update pull request handling logic.
No
=> Update pull request handling logic

components/data-display/category.tsx
Closes #29
Wrapped Carousel in Box for layout.
No
=> Wrapped Carousel in Box for layout

components/media-and-icons/color.tsx, components/media-and-icons/discord.tsx, components/media-and-icons/github.tsx
Closes #31 
Adjusted icon sizes and strokes.
No
=> Adjusted icon sizes and strokes

scripts/observe-pull-requests.ts
Increased reviewer count in script.
No
=> Increased reviewer count in script

components/form/search-color.tsx, components/layouts/header.tsx, components/navigation/tree.tsx, contexts/app-context.tsx, contexts/i18n-context.tsx, functions/get-random-colors.ts, hooks/use-event-listener.ts, pages/palettes/[uuid]/hexes.tsx, tsconfig.json, utils/color.ts, utils/i18n.ts, utils/random-color.ts, utils/storage.ts
Improved optional chaining and null checks.
No
=> Improved optional chaining and null checks

theme/semantics.ts
Closes #40 
Updated color codes for muted colors.
No
=> Updated color codes for muted colors

scripts/observe-pull-requests.ts
Related yamada-ui/yamada-ui#2099
Updated discord notification groups in scripts.
No
=> Updated discord notification groups in scripts 

.github/workflows/observe-issue-and-pull-request.yml, .github/workflows/reviewer-pull-request.yml, package.json, scripts/observe-issues.ts, scripts/observe-pull-requests.ts, scripts/reviewer-pull-requests.ts, scripts/utils.ts
Related yamada-ui/yamada-ui#2100
Added GitHub actions for issue and PR monitoring.
No
=> Added GitHub actions for issue and PR monitoring

.github/composite-actions/install/action.yml
Updated pnpm action to v3.0.0.
See https://github.com/yamada-ui/yamada-colors/actions/runs/9818156946/job/27110365515
No
=> Updated pnpm action to v3.0.0

.github/workflows/sync.yml
Updated create-pull-request action to v6.
No
=> Updated create-pull-request action to v6

.github/workflows/observe-issue-and-pull-request.yml
Adjusted JSON formatting in script.
No
=> Adjusted JSON formatting in script

.github/workflows/sync.yml
Updated token in GitHub workflow.
No
=> Updated token in GitHub workflow

package.json
Updated node version and pnpm.
No
=> Updated node version and pnpm

.github/composite-actions/install/action.yml, package.json, pnpm-lock.yaml
Update pnpm version and action setup.
No
=> Update pnpm version and action setup

.github/workflows/observe-issue-and-pull-request.yml
Updated JSON body structure in CI workflow
No
=> Updated JSON body structure in CI workflow

@types/colors.d.ts, pages/contrast-checker/contrast-checker.tsx, pages/contrast-checker/contrast-score.tsx, pages/contrast-checker/contrast-search.tsx, pages/contrast-checker/index.page.tsx
Closes #58
Add ColorContrast types and logic.
No
=> Add ColorContrast types and logic

components/other/copy-text.tsx
Updated styling and simplified icon logic.
No
=> Updated styling and simplified icon logic

.github/workflows/observe-issue-and-pull-request.yml
Updated curl request in CI workflow.
No
=> Updated curl request in CI workflow

utils/color.ts
Closes #67
I think it cant resolve the problem, but if keep origin color and converting tones it will be resolve
The reason I chose to keep the original color is because the format of hsl has different saturation than hex and rgb, so changes may occur when converted back to hex code.
A conditional statement to maintain the original color was added to the utils/color.ts/tones function.
Among the 11 colors, the 1st to 5th colors are light and the 7th to 11th colors are dark to maintain the original color.
```
export const tone = (hex: string) => {
const [h, s, l] = toHsl(hex)
const hexes: string[] = []
const d = l <= 50
const x = ((!d ? 100 : 95) - l) / 5
const y = (l - (d ? 5 : 15)) / 5
tones.forEach((tone) => {
const t = tone / 100
let z: number = l
let origin: boolean = false
if (t < 5) …
```
=> fix(color.ts): keep origin color and converting tones

pages/palettes/[uuid]/hex-control-buttons.tsx
Closes #69
Added useUpdateEffect in EditButton.
No
=> Added useUpdateEffect in EditButton

functions/get-random-colors.ts, package.json, pages/colors/[hex]/index.page.tsx, pnpm-lock.yaml, utils/color.ts
Closes #72
Updated generate tones.
No
=> Updated generate tones

.github/ISSUE_TEMPLATE/bug_report.ja.yml, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.ja.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Closes #79
Updated issue template labels for triage.
No
=> Updated issue template labels for triage

package.json, pnpm-lock.yaml
Update package dependencies versions.
No
=> Update package dependencies versions

lefthook.yaml
Update hooks and extend post-merge actions.
No
=> Update hooks and extend post-merge actions

components/data-display/category.tsx, components/data-display/color-card.tsx, components/feedback/copied-color-notice.tsx, components/feedback/index.ts, components/form/index.ts, components/form/palette-color-form.tsx, components/form/palette-menu.tsx, components/other/copy-text.tsx, components/overlay/color-command-menu.tsx, components/overlay/index.ts, components/overlay/palette-command-menu.tsx, components/overlay/palette-rename-modal.tsx, constant/enum.ts, constant/index.ts, contexts/i18n-context.tsx, i18n/ui.en.json, i18n/ui.ja.json, pages/colors/[hex]/a11y.tsx, pages/colors/[hex]/others.tsx, pages/generators/hexes.tsx, pages/generators/index.page.tsx, pages/generators/tabs.tsx, pages/palettes/[uuid]/context.ts, pages/palettes/[uuid]/header.tsx, pages/palettes/[uuid]/hex-control-buttons.tsx, pages/palettes/[uuid]/hexes.tsx, pages/palettes/palettes.tsx
Closes #27
Added context menu.
No
=> Added context menu

.github/workflows/sync.yml
Updated commit message in sync workflow.
No
=> Updated commit message in sync workflow

components/form/palette-color-form.tsx, pages/palettes/[uuid]/hex-control-buttons.tsx
Add useUpdateEffect for input and color changes.
No
=> Add useUpdateEffect for input and color changes

.github/workflows/sync.yml
Updated token in sync workflow.
No
=> Updated token in sync workflow

.gitignore
=> Update ignored files list

theme/tokens/fonts.ts, theme/tokens/index.ts
Added fonts tokens to theme configuration.
Currently, downloading `inter` but did not use it in the application.
No
=> Added fonts tokens to theme configuration

i18n/ui.en.json
Corrected spelling errors in JSON titles.
No
=> Corrected spelling errors in JSON titles
